### ISSUE TITLE
WebSocket as alternative to polling?

### ISSUE THREAD

**Issue by sje30** [lgatto/plothistory#1]
Just looked through your repo; looks great.

One thought: instead of running plothistory.R with continuous loop, delaying every 1s, you could use the WebSocket R package.
It's a bit more work though, but feels more elegant!

Also, I scratched my head when seeing two plothistory.R files -- perhaps the one in the inst/ folder could be given a "-poll.R" suffix to make it clear that it is the one doing the polling.

One advantage of this approach is that your package might work simpler for those running R remotely via TRAMP/ESS.

**Comment by lgatto** [comment]
Thank you!

I've [renamed](https://github.com/lgatto/plothistory/commit/db43dcb899dd5084a7f1ee44602f23f72493ba0c) the file to `inst/script/poll.R`. 

I'll look into websockets as soon as I get some free time on my hands.

**Comment by lgatto** [comment]
Done. It wasn't too difficult after all using the [websocket](https://rstudio.github.io/websocket/index.html) package :-)
