### ISSUE TITLE
init folder cannot be relative filename

### ISSUE THREAD

**Issue by sje30** [lgatto/plothistory#2]
hi Laurent,

```
cd
mkdir oo
R
require(plothistory)
plothistory(phdir='oo')
plot(1:10)

```

creates the wrong symbolic link in oo

```
$ ls -alR oo
oo:
total 258
drwx------   2 sje30 cbi-grp    5 Mar 27 11:15 ./
drwx-----x 164 sje30 cbi-grp  404 Mar 27 11:06 ../
-rw-------   1 sje30 cbi-grp  652 Mar 27 11:15 616b9eb67b65b288400dfd8cf012dbb8.svg
-rw-------   1 sje30 cbi-grp 4221 Mar 27 11:15 7fa407fda58d2d77c84813ebc6607a23.svg
lrwxrwxrwx   1 sje30 cbi-grp   39 Mar 27 11:15 .last.svg -> oo/7fa407fda58d2d77c84813ebc6607a23.svg
sje30@macro:~ $ file .last.svg
.last.svg: cannot open `.last.svg' (No such file or directory)
```

The fix for me was to pass phdir as an absolute pathname, not a relative directory.

**Comment by lgatto** [comment]
Thank you, will look into it.

**Comment by lgatto** [comment]
I think this should be addressed in the [latest commit](https://github.com/lgatto/plothistory/commit/069be790fe787b2414640845c2a9b691e8913e0c). That's at least what the [unit test](https://github.com/lgatto/plothistory/blob/main/tests/testthat/test-plothistory.R) claims.
